version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: blade-turbine-frontend:latest
    container_name: blade-turbine-frontend
    ports:
      - "3000:80"
    restart: unless-stopped

networks:
  blade-turbine-network:
    driver: bridge